name: karee_core
description: Karee core files, Karee core represents a set of amazing libraries, that work together to offer very powerful MVC experience in Flutter App Development
version: 2.0.0
homepage: https://github.com/ChamplainLeCode/karee_core

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  screen_tracker: ^2.0.0
  reflectable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/