name: karee
description: Another way to build Flutter applications using the power of MVC Design Pattern.
version: 2.2.0
homepage: https://github.com/ChamplainLeCode/karee
environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  karee_inject: ^1.0.3
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/