name: karee
description: Another way to build Flutter applications using the power of MVC Design Pattern.
version: 2.1.0
homepage: https://github.com/ChamplainLeCode/karee
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  karee_inject: ^1.0.2
  yaml: ^3.1.0
  reflectable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/